### ISSUE TITLE
Styling in popups isn't sufficiently reset

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-connectors#79]
On zotero.org, for example, the buttons take on the site style and become red.

I've used something like this before to decent effect:
```css
.popup {
	all: initial;
}
.popup all {
	all: unset;
}
```
(Safari [might need to](https://developer.mozilla.org/en-US/docs/Web/CSS/all#Browser_compatibility) use `all: revert` instead.)
